NumPy arrays are like “lists” — but better because it’s (1) faster, (2) more convenient, and (3) takes up less memory


In [1]:
!pip install numpy

You should consider upgrading via the 'c:\python\python38\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

There are different ways of creating an array, but this is the simplest method. You can create one or more dimensional arrays.
np array creates an array np.array([1,2,3]) one dimensional or 2 dimensional np.array([[1,2,3],[4,5,6]])

In [3]:
english_grade = [100,90,92,95,70,84,80,75,89]
E = np.array(english_grade)
print(E)


[100  90  92  95  70  84  80  75  89]


Creates an array start,stop, step

In [6]:
print(np.arange(1,10,2))


[1 3 5 7 9]


Similar to arange but use sample number, 
start,stop, num. Give me 4 evenly space numbers within 1 and 10 

Возвращает одномерный массив из указанного количества элементов, значения которых равномерно распределенны внутри заданного интервала. 

In [7]:
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


Gives an element without chaning it data
You can see that in this example, there are three elements (starting with 0, 4, 8) on axis 0, and four elements on axis 1 (starting with 0, 1, 2, 3).


In [8]:
resh = np.arange(12).reshape(3,4)
print(resh)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


For axis 0, you get 12 as the first element because 0 + 4 + 8 = 12.
For axis 1, you get 6 as the first element because 0 + 1 + 2 + 3 = 6.

In [9]:
sum0 = np.sum(resh, axis=0)
sum1 = np.sum(resh, axis=1)
print(sum0)
print(sum1)

[12 15 18 21]
[ 6 22 38]


Returns the variance (дисперсия) of the array of the elements along the specified axis

In [10]:
print(np.var(np.array([[1,2],[3,4]])))

1.25


Returns the standart deviation

In [37]:
print(np.std(np.array([[1,2],[3,4]])))

1.118033988749895


Shuffle the array along the first axis of a multu-dimenstional array

In [11]:
english_grade = [100,90,92,95,70,84,80,75,89]
np.random.shuffle(english_grade)
print(english_grade)

[70, 90, 92, 100, 95, 84, 80, 75, 89]


Extract part of array,
start, stop, index

In [12]:
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(s)
print(a[s])
# from 2 to 7 with step 2
t = a[2:7:2]
print(t)

[0 1 2 3 4 5 6 7 8 9]
slice(2, 7, 2)
[2 4 6]
[2 4 6]


Return contigious flattened array 

In [40]:
print(np.ravel(resh))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
